import { ArrowLeft, DatabaseBackup, Download, Plus, RefreshCw, RotateCcw, Save, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ADMIN_SESSION_KEY, createBackup, deleteBackup, downloadBackup, fetchBackupConfig, fetchBackups, restoreBackup, saveBackupConfig, testBackupConnection, verifyAdminSession } from "@/lib/api";
import type { BackupConfig, BackupRecord } from "@/types";

const initialConfig: BackupConfig = { endpoint: "", region: "", bucket: "", keyPrefix: "", accessKeyId: "", secretAccessKey: "", forcePathStyle: false, scheduleEnabled: false, cronExpression: "0 2 * * *", retentionDays: 14, maxBackups: 10 };

export default function AdminBackup() {
  const navigate = useNavigate();
  const [config, setConfig] = useState<BackupConfig>(initialConfig);
  const [backups, setBackups] = useState<BackupRecord[]>([]);
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const reload = useCallback(async () => { const [nextConfig, nextBackups] = await Promise.all([fetchBackupConfig(), fetchBackups()]); setConfig({ ...nextConfig, secretAccessKey: "" }); setBackups(nextBackups); }, []);
  useEffect(() => { void verifyAdminSession().then(reload).catch(() => { localStorage.removeItem(ADMIN_SESSION_KEY); navigate("/admin/login"); }); }, [navigate, reload]);
  const update = <K extends keyof BackupConfig>(key: K, value: BackupConfig[K]) => setConfig((current) => ({ ...current, [key]: value }));
  const run = async (action: () => Promise<void>) => { setBusy(true); setMessage(""); try { await action(); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } finally { setBusy(false); } };
  const formatSize = (size: number) => `${(size / 1024 / 1024).toFixed(2)} MB`;
  return <main className="min-h-screen bg-[#08111f] px-4 py-6 text-slate-100 lg:px-8"><div className="mx-auto max-w-[1400px]">
    <header className="mb-6 flex flex-col gap-4 rounded-[28px] border border-white/10 bg-white/[0.04] p-5 lg:flex-row lg:items-center lg:justify-between"><div><Link className="mb-3 inline-flex items-center gap-2 text-sm text-cyan-200 hover:text-white" to="/admin"><ArrowLeft className="h-4 w-4" /> 返回管理页面</Link><h1 className="text-3xl font-black text-white">数据备份</h1><p className="mt-2 text-sm text-slate-400">配置 S3 存储、定时备份，并管理本地或远端备份记录。</p></div><button className="action-button" disabled={busy} onClick={() => run(async () => { await reload(); setMessage("备份记录已刷新"); })}><RefreshCw className="h-4 w-4" /> 刷新</button></header>
    {message && <div className="mb-5 rounded-2xl border border-cyan-300/30 bg-cyan-300/10 px-4 py-3 text-sm text-cyan-100">{message}</div>}
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-[28px] border border-slate-700/70 bg-slate-950/70 p-5"><h2 className="mb-4 flex items-center gap-2 text-lg font-bold"><DatabaseBackup className="h-5 w-5 text-cyan-300" /> S3 存储配置</h2>{([['endpoint','端点地址'],['region','区域'],['bucket','存储桶'],['keyPrefix','Key 前缀'],['accessKeyId','Access Key ID']] as const).map(([key,label]) => <label key={key} className="admin-label">{label}<input disabled={busy} className="admin-input" value={config[key]} onChange={(e) => update(key, e.target.value)} /></label>)}<label className="admin-label">Secret Access Key<input disabled={busy} className="admin-input" type="password" value={config.secretAccessKey || ""} placeholder={config.hasSecretAccessKey ? "已保存，留空不修改" : "仅保存在服务器"} onChange={(e) => update('secretAccessKey', e.target.value)} /></label><label className="mt-4 flex items-center gap-2 text-sm text-slate-300"><input disabled={busy} type="checkbox" checked={config.forcePathStyle} onChange={(e) => update('forcePathStyle', e.target.checked)} /> 强制路径风格</label><div className="mt-5 grid grid-cols-2 gap-3"><button className="secondary-download" disabled={busy} onClick={() => run(async () => setMessage(await testBackupConnection()))}>测试连接</button><button className="download-button" disabled={busy} onClick={() => run(async () => { const next = await saveBackupConfig(config); setConfig({ ...next, secretAccessKey: "" }); await reload(); setMessage("备份配置已保存"); })}><Save className="h-4 w-4" /> 保存</button></div></section>
    <section className="rounded-[28px] border border-slate-700/70 bg-slate-950/70 p-5"><h2 className="mb-4 text-lg font-bold">定时备份</h2><label className="flex items-center gap-2 text-sm text-slate-300"><input disabled={busy} type="checkbox" checked={config.scheduleEnabled} onChange={(e) => update('scheduleEnabled', e.target.checked)} /> 启用定时备份（需要完整 S3 配置）</label><label className="admin-label">Cron 表达式<input disabled={busy} className="admin-input" value={config.cronExpression} onChange={(e) => update('cronExpression', e.target.value)} /></label><label className="admin-label">过期天数（0 为不过期）<input disabled={busy} className="admin-input" type="number" min="0" value={config.retentionDays} onChange={(e) => update('retentionDays', Number(e.target.value))} /></label><label className="admin-label">最大保留数量（0 为不限制）<input disabled={busy} className="admin-input" type="number" min="0" value={config.maxBackups} onChange={(e) => update('maxBackups', Number(e.target.value))} /></label><button className="download-button mt-5 w-full" disabled={busy} onClick={() => run(async () => { const next = await saveBackupConfig(config); setConfig({ ...next, secretAccessKey: "" }); await reload(); setMessage("定时备份设置已保存"); })}><Save className="h-4 w-4" /> 保存定时设置</button></section></div>
    <section className="mt-5 rounded-[28px] border border-slate-700/70 bg-slate-950/70 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold">备份记录</h2><button className="download-button" disabled={busy} onClick={() => run(async () => { await createBackup(); await reload(); setMessage("本地备份已创建"); })}><Plus className="h-4 w-4" /> 手动创建</button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-slate-400"><tr><th className="pb-3">状态</th><th>文件名</th><th>大小</th><th>存储</th><th>触发方式</th><th>开始时间</th><th>到期时间</th><th>操作</th></tr></thead><tbody>{backups.map((backup) => <tr key={backup.id} className="border-t border-slate-800"><td className={backup.status === 'completed' ? 'text-emerald-300' : 'text-rose-300'}>{backup.status}</td><td className="max-w-48 truncate py-3">{backup.fileName}</td><td>{formatSize(backup.size)}</td><td>{backup.storage}</td><td>{backup.trigger}</td><td>{new Date(backup.createdAt).toLocaleString()}</td><td>{backup.expiresAt ? new Date(backup.expiresAt).toLocaleString() : '永久'}</td><td><div className="flex gap-2"><button disabled={busy} className="mini-button" onClick={() => run(async () => { const blob = await downloadBackup(backup.id); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = backup.fileName; link.click(); URL.revokeObjectURL(url); })}><Download className="h-3 w-3" /> 下载</button><button disabled={busy || !backup.restoreAvailable} title={!backup.restoreAvailable ? "仅本地可用的备份可以恢复" : undefined} className="mini-button" onClick={() => { if (window.confirm('恢复会覆盖当前元数据、文件和任务，确认继续？')) void run(async () => { setMessage(await restoreBackup(backup.id)); await reload(); }); }}><RotateCcw className="h-3 w-3" /> 恢复</button><button disabled={busy} className="mini-button text-rose-300" onClick={() => { if (window.confirm('确认删除该备份？')) void run(async () => { const warning = await deleteBackup(backup.id); await reload(); setMessage(warning || '备份已删除'); }); }}><Trash2 className="h-3 w-3" /> 删除</button></div>{!backup.restoreAvailable && <p className="mt-1 text-xs text-slate-500">仅本地可用备份可恢复</p>}</td></tr>)}{!backups.length && <tr><td colSpan={8} className="py-8 text-center text-slate-500">暂无备份记录</td></tr>}</tbody></table></div></section>
  </div></main>;
}
